### PR TITLE
add teal part + add teal pkgs + update .lock file

### PR DESCRIPTION
**Pull request by pawelru**

### CODE REVIEW

**Review by thebioengineer — COMMENTED** [review]
I think everything seems fine, my only concern is that is a lot of content to cover in an hour and a half. Is some just here's some background info, or do you plan to have folks spend time on each section?

**Comment by pawelru** [comment]
Some of them are definitely just for a demo. My initial plan is to do 1-5 quickly (5 mins each) and leave much more time for 07-01 (ARD) to work on their own. I consider 07-02 and 07-03 as extras. I can showoff at the very end.

**Comment by thebioengineer** [comment]
Works for me if that's the plan. Any slides you plan to use too, or "just" this?

**Comment by pawelru** [comment]
This is still in progress. I am working on adjusting the master slide deck we have to the conference content - in particular the exercises part. Will submit in the coming days. In the meantime - would you be able to go through the 07-XX parts (scroll down to the answers) and check if it makes sense from the business perspective? Or any super obvious mistake of mine?

**Pull request merged**
